[tool.poetry]
name = "test_software"
version = "1.0.0"
description = ""
authors = ["JunKubota"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
pytest = "^7.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"